package com.comp2042.controller;

import com.comp2042.controller.keyInput.KeyInputHandler;
import com.comp2042.events.*;
import com.comp2042.model.logic.GameMode;
import com.comp2042.model.logic.GameTime;
import com.comp2042.model.logic.MovingDownData;
import com.comp2042.view.data.ViewData;
import com.comp2042.view.scenes.GameOverPanel;
import com.comp2042.view.scenes.GamePausePanel;
import com.comp2042.view.soundBoard.Sound;
import javafx.beans.property.IntegerProperty;
import javafx.beans.property.StringProperty;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.Group;
import javafx.scene.input.KeyEvent;
import javafx.scene.layout.GridPane;
import javafx.scene.text.Font;
import javafx.scene.text.Text;
import javafx.scene.layout.Pane;

import java.net.URL;
import java.util.Objects;
import java.util.ResourceBundle;

/**
 * The main JavaFX Controller for the game screen ({@code gameLayout.fxml}).
 *
 * <p>This class is a central orchestrator, managing all visual components and coordinating
 * the flow between user input, game logic (via {@code GameController}), and rendering (via
 * {@code GameRenderer}). It initializes and manages several helper classes to adhere to
 * the **Single Responsibility Principle (SRP)**.</p>
 *
 * <p>Design Patterns Implemented:</p>
 * <ul>
 * <li>**Model-View-Controller (MVC)**: Acts as the **View** by presenting the game state, and as a **Controller** by handling user input and delegating state changes.</li>
 * <li>**Composition/Dependency Injection**: It delegates responsibilities to dedicated classes (e.g., {@code GameRenderer}, {@code GameFlowManager}, {@code KeyInputHandler}, etc.) rather than containing all logic itself.</li>
 * <li>**Observer Pattern (via Data Binding)**: It observes observable properties from the model (Score, Level, Lines, Time) and automatically updates the corresponding UI elements when they change.</li>
 * </ul>
 */
public class GuiController implements Initializable {

    @FXML private GridPane gamePanel;
    @FXML private GridPane brickPanel;
    @FXML private GridPane nextBrick;
    @FXML private GridPane shadowPanel;
    @FXML private GridPane holdBrick;
    @FXML private Group groupNotification;
    @FXML private Group levelUpNotification;
    @FXML private GameOverPanel gameOverPanel;
    @FXML private Text scoreValue;
    @FXML private Text gameTime;
    @FXML private Text countRowsValue;
    @FXML private Text levelValue;
    @FXML private Pane rootPane;

    private InputEventListener eventListener;
    private GameRenderer gameRenderer;
    private GameFlowManager gameFlow;
    private Notifications notification;
    private KeyInputHandler keyHandler;
    private GamePausePanel gamePausePanel;

    private final Sound bgm = new Sound();
    private final Sound sfx = new Sound();

    /**
     * Initializes the controller, loads resources, sets up helper classes, and initializes
     * key event handling.
     *
     * @param location The location used to resolve relative paths for the root object, or null if the location is not known.
     * @param resources The resources used to localize the root object, or null if the root object was not localized.
     */
    @Override
    public void initialize(URL location, ResourceBundle resources) {
        Font.loadFont(Objects.requireNonNull(getClass().getClassLoader().getResource("digital.ttf")).toExternalForm(), 38);

        gameRenderer = new GameRenderer(brickPanel, gamePanel, nextBrick, shadowPanel, holdBrick);
        gameFlow = new GameFlowManager(gamePanel, null);
        notification = new Notifications(groupNotification, levelUpNotification);
        gamePausePanel = new GamePausePanel(rootPane);
        gameOverPanel = new GameOverPanel(rootPane);

        gamePausePanel.loadPauseScreen();

        initializeKeyControls();
        gameOverPanel.loadGameOverPanel();

        bgm.bgMusic();
    }

    /**
     * Configures the {@code gamePanel} to be focusable and sets up the key press event handler
     * to capture all keyboard inputs for the game.
     */
    private void initializeKeyControls() {
        gamePanel.setFocusTraversable(true);
        gamePanel.requestFocus();
        gamePanel.setOnKeyPressed(this::handleAllKeys);
    }

    /**
     * The unified handler for all key press events.
     * Delegates input handling to {@code KeyInputHandler} based on the current game state
     * (paused or game over).
     *
     * @param keyEvent The JavaFX {@code KeyEvent} generated by the user.
     */
    private void handleAllKeys(KeyEvent keyEvent) {
        if (gameFlow.isPause().getValue() == Boolean.FALSE && gameFlow.isGameOver().getValue() == Boolean.FALSE) {
            switch (keyEvent.getCode()) {
                case UP, W -> sfx.soundEffects(1);
            }
            keyHandler.handleBrickControlKeys(keyEvent, this::moveDown, this::refreshBrick, this::hardDrop);
        }
        keyHandler.handleGlobalKeys(keyEvent);
    }

    /**
     * Initializes the game view and starts the game timers. Called once by {@code GameController} after setup.
     *
     * @param boardMatrix The initial state of the game board.
     * @param brick The initial view data of the falling brick.
     */
    public void initializeGameView(int[][] boardMatrix, ViewData brick) {
        gameRenderer.initializeRenderingState(boardMatrix, brick);

        gameFlow.createTimeline(() -> moveDown(new MoveEvent(EventType.DOWN, EventSource.THREAD)));
        gameFlow.createRisingRowTimeline(this::handleRisingRowAddition);
        gameFlow.start();
    }

    /**
     * Handles the periodic call from the {@code GameFlowManager} to check and execute
     * the rising row addition logic.
     * It only executes if the game is currently running and not paused/over.
     */
    private void handleRisingRowAddition() {
        if (gameFlow.isPause().getValue() == Boolean.FALSE && gameFlow.isGameOver().getValue() == Boolean.FALSE) {
            ((GameController) eventListener).onRisingRowEvent();
        }
    }

    /**
     * The internal method used to refresh the view of the falling brick, ghost piece,
     * next brick panel, and held brick panel. It is guarded against execution while paused.
     *
     * @param brick The updated {@code ViewData} containing all position and shape information.
     */
    private void refreshBrick(ViewData brick) {
        if (gameFlow.isPause().getValue() == Boolean.FALSE) {
            gameRenderer.refreshBrick(brick);
            gameRenderer.generateNextBrickInPreviewPanel(brick.getNextBrickData());
            gameRenderer.generateHoldBrickInPanel(brick.getHeldBrickData());
        }
    }

    /**
     * Updates the display of the current falling brick and preview panels.
     * @param brick The updated view data.
     */
    public void updateView(ViewData brick) {
        refreshBrick(brick);
    }

    /**
     * Updates the display of the merged blocks on the main game board background.
     * @param board The updated game board matrix.
     */
    public void refreshGameBackground(int[][] board) {
        gameRenderer.refreshGameBackground(board);
    }

    /**
     * Executes the main move-down logic. This method is called by the automatic game thread
     * or by user soft-drop input.
     *
     * <p>Delegates the movement to {@code GameController}, handles line-clear feedback (sound, notification),
     * and updates the view.</p>
     *
     * @param event The move event details.
     */
    private void moveDown(MoveEvent event) {
        if (gameFlow.isPause().getValue() == Boolean.FALSE) {
            MovingDownData movingDownData = eventListener.onDownEvent(event);
            if (movingDownData.getClearRow() != null && movingDownData.getClearRow().getLinesRemoved() > 0) {
                for (int i = 0; i < movingDownData.getClearRow().getLinesRemoved(); i++) {
                    sfx.soundEffects(2);
                }
                notification.showScore(movingDownData.getClearRow().getScoreBonus());
            }
            refreshBrick(movingDownData.getViewData());
        }
        gamePanel.requestFocus();
    }

    /**
     * Sets the {@code InputEventListener} (the {@code GameController}) and initializes the {@code KeyInputHandler}.
     * @param eventListener The game logic controller.
     */
    public void setEventListener(InputEventListener eventListener) {
        this.eventListener = eventListener;
        this.keyHandler = new KeyInputHandler(eventListener, this::newGame, this::pauseGame);
        gameFlow.setEventListener(eventListener);
    }

    /**
     * Passes the {@code GameTime} instance to the {@code GameFlowManager}.
     * @param gameTime The game time instance.
     */
    public void setGameTimer(GameTime gameTime) {
        gameFlow.setGameTimer(gameTime);
    }

    /**
     * Notifies the {@code GameFlowManager} of a level change to adjust the brick falling speed.
     * @param newLevel The current game level.
     */
    public void updateGameSpeed(int newLevel) {
        gameFlow.updateSpeed(newLevel);
    }

    /**
     * Passes the selected game mode to the {@code GameFlowManager} for speed/rising row logic.
     * @param gameMode The game mode.
     */
    public void setGameMode(GameMode gameMode) {
        if (gameFlow != null) {
            gameFlow.setGameMode(gameMode);
        }
    }

    /**
     * Binds the model's score property to the UI text element for live updates.
     * @param integerProperty The score property from the model.
     */
    public void bindScore(IntegerProperty integerProperty) {
        scoreValue.textProperty().bind(integerProperty.asString());
    }

    /**
     * Binds the model's time string property to the UI text element.
     * @param stringProperty The time string property from the model.
     */
    public void bindTimer(StringProperty stringProperty) {
        gameTime.textProperty().bind(stringProperty);
    }

    /**
     * Binds the model's line count property to the UI text element, formatting it as a three-digit zero-padded number.
     * @param integerProperty The line count property from the model.
     */
    public void bindLines(IntegerProperty integerProperty) {
        countRowsValue.textProperty().bind(integerProperty.asString("%03d"));
    }

    /**
     * Binds the model's level property to the UI text element.
     * @param integerProperty The level property from the model.
     */
    public void bindLevel(IntegerProperty integerProperty) {
        levelValue.textProperty().bind(integerProperty.asString());
    }

    /**
     * Handles the game over sequence: stops game flow, saves final stats via {@code GameController},
     * displays the game over panel, and plays the game over sound effect.
     */
    public void gameOver() {
        gameFlow.gameOver();

        if (eventListener instanceof GameController gameController) {
            gameController.getFinalGameStats();
        }

        gameOverPanel.showPanel(gameFlow);
        bgm.stop();
        sfx.soundEffects(3);
    }

    /**
     * Handles the initiation of a new game, typically triggered by the 'N' key.
     *
     * <p>Delegates the new game command to {@code GameFlowManager}, hides game state panels,
     * and restarts the background music.</p>
     *
     * @param actionEvent The event that triggered the action (ignored).
     */
    private void newGame(ActionEvent actionEvent) {
        gameFlow.newGame();
        gamePausePanel.showPanel(gameFlow);
        gameOverPanel.showPanel(gameFlow);
        gamePanel.requestFocus();
        bgm.bgMusic();
    }

    /**
     * Toggles the game's pause state, typically triggered by the 'ESCAPE' key.
     *
     * <p>Prevents pausing if the game is over. Stops or resumes background music and toggles the
     * visibility of the pause panel.</p>
     *
     * @param actionEvent The event that triggered the action (ignored).
     */
    private void pauseGame(ActionEvent actionEvent) {
        // Does not apply the pause game method when game over is true
        if (gameFlow.isGameOver().getValue() == Boolean.TRUE) {
            return;
        }

        gameFlow.pauseGame();

        if (gameFlow.isPause().getValue()) {
            bgm.stop();
        } else {
            bgm.resume();
        }

        gamePausePanel.showPanel(gameFlow);
        gamePanel.requestFocus();
    }

    /**
     * Handles the hard drop (Slam) action triggered by the SPACE key.
     * Delegates the continuous drop and landing logic to the {@code GameController}.
     *
     * @param event The move event details.
     */
    public void hardDrop(MoveEvent event) {
        if (gameFlow.isPause().getValue() == Boolean.FALSE) {

            MovingDownData movingDownData = eventListener.onSlamEvent(event);

            if (movingDownData.getClearRow() != null && movingDownData.getClearRow().getLinesRemoved() > 0) {
                sfx.soundEffects(2);
                notification.showScore(movingDownData.getClearRow().getScoreBonus());
            }
            refreshBrick(movingDownData.getViewData());
        }
        gamePanel.requestFocus();
    }

    /**
     * Triggers the animated pop-up notification when the player advances a level.
     * @param level The new level achieved.
     */
    public void showLevelUpNotification(int level) {
        notification.showLevelUp(level);
    }
}
